version: "3.7"

volumes:
  storemanagementdb:
  medicalfiledb:


services:
  storemanagement:
    image: storemanagement
    ports:
      - 9100:8085
    depends_on:
      - storemanagementdb

  storemanagementdb:
    image: mysql
    ports:
      - 12000:3306
    environment:
      - MYSQL_DATABASE=storemanagement
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - storemanagementdb:/var/lib/mysql

  medicalfile:
    image: medicalfile
    ports:
      - 9101:8086
    depends_on:
      - medicalfiledb

  medicalfiledb:
    image: mysql
    ports:
      - 12001:3306
    environment:
      - MYSQL_DATABASE=medicalfile
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - medicalfiledb:/var/lib/mysql
